### ISSUE TITLE
一份十分不完整的数据集……

### ISSUE THREAD

**Issue by KOOOYTO** [hustvl/HDR-HexPlane#1]
Google硬盘里上传的数据不全，airplane、hook等文件夹中train和test都是空的😭希望可以把image文件夹压缩再上传呢？

**Comment by guanjunwu** [comment]
e, I'll upload all the zip files by BaiduYun soon.
[this](https://pan.baidu.com/s/1vuJ5kThgRkmv9DWis9g8Pg?pwd=1234) is the full dataset link.

**Comment by KOOOYTO** [comment]
> e, I'll upload all the zip files by BaiduYun soon. [this](https://pan.baidu.com/s/1vuJ5kThgRkmv9DWis9g8Pg?pwd=1234) is the full dataset link.

您的回复很有帮助，非常感谢！
因为想要复现并进一步修改这篇工作，所以正在尝试训练，但是结果并不如意：下图是训练tank一万轮次的情况，但是在两万轮次时train psnr在32左右，而test psnr仍然只有16左右：
<img width="786" alt="Untitled" src="https://github.com/hustvl/HDR-HexPlane/assets/74454660/ed856e40-2706-4c5d-ba40-65a410fa402d">
看保存的图像也发现曝光学习的结果十分令人诧异，并不能正确地集中到三个曝光值上：
![Untitled2](https://github.com/hustvl/HDR-HexPlane/assets/74454660/004e04e5-88c9-49ed-892e-82a6b26f87b0)

请问这可能是什么原因呢？

**Comment by guanjunwu** [comment]
你好，我把新版本传上去了，之前的版本有点bug，麻烦再试试，如果有问题随时联系我

**Comment by KOOOYTO** [comment]
谢谢🥺🌹



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月3日(周日) 下午5:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hustvl/HDR-HexPlane] 一份十分不完整的数据集…… (Issue #1)




 
不好意思，我好像传错版本了，马上把新版本传上去

**Comment by NEUCNWL** [comment]
您好，小鹿的blender是不是有点bug，运行时并不是动态的。

**Comment by guanjunwu** [comment]
> 您好，小鹿的blender是不是有点bug，运行时并不是动态的。

你看他的blender文件，他会跳起来的
