### ISSUE TITLE
Regarding Datset

### ISSUE THREAD

**Issue by GopiRajuMatta** [hustvl/HDR-HexPlane#2]
Hello!

Thank you for open sourcing a very nice work of yours. 

Regarding your dataset, I could only find blender files, not actual multi-exposure images.

Can you please share that as well as a google drive link.

Thank you
Gopi

**Comment by TejasCThakare** [comment]
Yes, I am also looking for the dataset. Can you please update the Google Drive link for the full dataset.

**Comment by guanjunwu** [comment]
hello, I've update dataset to huggingface, just look at readme file.

**Comment by GopiRajuMatta** [comment]
I could download the dataset from huggingface, thank you so much. But in Readme file, I couldn't find any information for the same. If that's the case, please do add.

Thank you
Gopi
